### ISSUE TITLE
Promise::finally()

### ISSUE THREAD

**Issue by Jviguy** [Jviguy/Promises#3]
# Missing Function
Promise::finally(callback(result, err))

## Implementation
Call the given callback no matter the result of the Promise.

**Comment by HashimTheArab** [comment]
Should the finally callback just be stored in 1 property in Promise.php?

**Comment by Jviguy** [comment]
Yes.

```php
//Should be something like this
/**
* @var $finals callback[] - the finally callbacks.
*/
private array $finals
```

**Comment by Jviguy** [comment]
This is added by #4 thx to @Prim69!
